services:
  nginx:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
    ports:
      - "8443:8443/tcp"
      - "8443:8443/udp"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs
